const data = {
    products: [
        {
            _id: '1',
            name: 'Zebra ZT4202',
            category: 'Imprimante',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Zebra',
            rating: 4.1,
            numReviews: 10,
            description: 'O imprimantă robustă, performantă, uşor de utilizat.',
        },
        {
            _id: '2',
            name: 'Zebra ZT220',
            category: 'Imprimante',
            image: '/images/p2.jpg',
            price: 120,
            brand: 'Zebra',
            rating: 4.5,
            numReviews: 10,
            description: 'hight quality product',
        },
        {
            _id: '3',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'hight quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p4.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'hight quality product',
        },
        {
            _id: '5',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p5.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 10,
            description: 'hight quality product',
        },
        {
            _id: '6',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p6.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.2,
            numReviews: 10,
            description: 'hight quality product',
        },
    ],
};
export default data;